/**
 * OpenAPI auto-aggregation
 *
 * Automatically generates an OpenAPI lambda that aggregates all routes
 * from all other lambdas to provide a complete API specification.
 */

import { join } from "path";
import { readdirSync } from "fs";
import type { ResolvedConfig } from "./config";

/**
 * Generate the OpenAPI aggregator lambda source code
 */
export function generateOpenApiLambdaSource(
	lambdaFiles: string[],
	config: ResolvedConfig,
): string {
	// Filter out any existing openapi file to avoid circular imports
	const routeFiles = lambdaFiles.filter(
		(f) => !f.includes("openapi") && !f.startsWith("__"),
	);

	const imports = routeFiles
		.map((file, index) => {
			const name = file.replace(/\.ts$/, "");
			return `import route${index} from "./${name}";`;
		})
		.join("\n");

	const uses = routeFiles.map((_, index) => `.use(route${index})`).join("\n\t\t");

	return `/**
 * Auto-generated OpenAPI aggregator lambda
 * Generated by elysia-apigw - DO NOT EDIT
 */

import Elysia from "elysia";
import { openapi } from "@elysiajs/openapi";
import { Hono } from "hono/tiny";
import { handle } from "hono/aws-lambda";

${imports}

const app = new Elysia()
	.use(
		openapi({
			documentation: {
				info: {
					title: ${JSON.stringify(config.openapi.title)},
					version: ${JSON.stringify(config.openapi.version)},
					description: ${JSON.stringify(config.openapi.description)},
				},
			},
		}),
	)
	${uses ? `\t${uses}` : ""};

export default app;

// Lambda handler
const api = new Hono().mount("/", app.fetch);
export const handler = handle(api);
`;
}

/**
 * Write the OpenAPI aggregator lambda to a temp location for bundling
 */
export async function writeOpenApiLambda(
	lambdaFiles: string[],
	lambdasDir: string,
	config: ResolvedConfig,
): Promise<string> {
	const source = generateOpenApiLambdaSource(lambdaFiles, config);
	const outputPath = join(lambdasDir, "__openapi__.ts");

	await Bun.write(outputPath, source);
	return outputPath;
}

/**
 * Check if OpenAPI aggregator needs to be generated
 */
export function shouldGenerateOpenApi(config: ResolvedConfig): boolean {
	return config.openapi.enabled;
}

/**
 * Clean up the generated OpenAPI lambda file
 */
export async function cleanupOpenApiLambda(lambdasDir: string): Promise<void> {
	const openApiPath = join(lambdasDir, "__openapi__.ts");
	try {
		const file = Bun.file(openApiPath);
		if (await file.exists()) {
			await Bun.write(openApiPath, ""); // Clear content
			const { unlinkSync } = await import("fs");
			unlinkSync(openApiPath);
		}
	} catch {
		// Ignore cleanup errors
	}
}
