/**
 * OpenAPI auto-aggregation
 *
 * Automatically generates an OpenAPI lambda that aggregates all routes
 * from API route lambdas (src/api/) to provide a complete API specification.
 *
 * Note: Only API routes are included in OpenAPI, not generic lambdas.
 */

import { join } from "path";
import type { ResolvedConfig } from "./config";
import type { DiscoveredApiRoute } from "./discovery";

/**
 * Resolve a module path from elysian's node_modules
 */
function resolveFromElysian(modulePath: string): string {
	try {
		const resolved = import.meta.resolve(modulePath);
		return resolved.replace("file://", "");
	} catch {
		return modulePath;
	}
}

/**
 * Generate the OpenAPI aggregator lambda source code
 * Only includes API routes from src/api/, not generic lambdas
 */
export function generateOpenApiLambdaSource(
	apiRoutes: DiscoveredApiRoute[],
	config: ResolvedConfig,
): string {
	// Filter out any existing openapi file to avoid circular imports
	const routeFiles = apiRoutes.filter(
		(r) => !r.name.includes("openapi"),
	);

	const imports = routeFiles
		.map((route, index) => {
			// Use absolute path to the lambda file
			return `import route${index} from "${route.sourcePath}";`;
		})
		.join("\n");

	const uses = routeFiles.map((_, index) => `.use(route${index})`).join("\n\t\t");

	// Resolve paths from elysian's dependencies
	const honoTinyPath = resolveFromElysian("hono/tiny");
	const honoLambdaPath = resolveFromElysian("hono/aws-lambda");
	const openapiPath = resolveFromElysian("@elysiajs/openapi");

	return `/**
 * Auto-generated OpenAPI aggregator lambda
 * Generated by elysian - DO NOT EDIT
 */

import Elysia from "elysia";
import { openapi } from "${openapiPath}";
import { Hono } from "${honoTinyPath}";
import { handle } from "${honoLambdaPath}";

${imports}

const app = new Elysia()
	.use(
		openapi({
			documentation: {
				info: {
					title: ${JSON.stringify(config.api.openapi.title)},
					version: ${JSON.stringify(config.api.openapi.version)},
					description: ${JSON.stringify(config.api.openapi.description)},
				},
			},
		}),
	)
	${uses ? `\t${uses}` : ""};

export default app;

// Lambda handler
const api = new Hono().mount("/", app.fetch);
export const handler = handle(api);
`;
}

/**
 * Write the OpenAPI aggregator lambda to a temp location for bundling
 */
export async function writeOpenApiLambda(
	apiRoutes: DiscoveredApiRoute[],
	config: ResolvedConfig,
	tempDir: string,
): Promise<string> {
	const source = generateOpenApiLambdaSource(apiRoutes, config);
	const outputPath = join(tempDir, "openapi.ts");

	await Bun.write(outputPath, source);
	return outputPath;
}

/**
 * Check if OpenAPI aggregator needs to be generated
 */
export function shouldGenerateOpenApi(config: ResolvedConfig): boolean {
	return config.api.openapi.enabled;
}

/**
 * Clean up the generated OpenAPI lambda file
 */
export async function cleanupOpenApiLambda(tempDir: string): Promise<void> {
	const openApiPath = join(tempDir, "openapi.ts");
	try {
		const file = Bun.file(openApiPath);
		if (await file.exists()) {
			await Bun.write(openApiPath, ""); // Clear content
			const { unlinkSync } = await import("fs");
			unlinkSync(openApiPath);
		}
	} catch {
		// Ignore cleanup errors
	}
}

// Legacy function for backwards compatibility
export function generateOpenApiLambdaSourceLegacy(
	lambdaFiles: string[],
	lambdasDir: string,
	config: ResolvedConfig,
): string {
	const apiRoutes: DiscoveredApiRoute[] = lambdaFiles.map((file) => ({
		name: file.replace(/\.ts$/, ""),
		sourcePath: join(lambdasDir, file.replace(/\.ts$/, "")),
		bundleName: `${config.name}-${file.replace(/\.ts$/, "")}`,
	}));
	return generateOpenApiLambdaSource(apiRoutes, config);
}
