/**
 * Terraform output generation
 */

import { join } from "path";
import ms from "ms";
import type { ApiManifest, GenericLambdaManifest } from "./manifest";
import type { ResolvedConfig } from "./config";
import { generateRouteName } from "./manifest";

/**
 * Convert ms-style duration string to AWS EventBridge rate expression
 *
 * AWS rate expressions only support: minute(s), hour(s), day(s)
 * @see https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html
 *
 * @example
 * "1h" -> "rate(1 hour)"
 * "30m" -> "rate(30 minutes)"
 * "1 day" -> "rate(1 day)"
 * "2 days" -> "rate(2 days)"
 */
export function convertMsToAwsRate(duration: string): string {
	// Parse the duration using ms package to get milliseconds
	const milliseconds = ms(duration as ms.StringValue);
	if (milliseconds === undefined) {
		throw new Error(`Invalid duration format: "${duration}". Use ms-style strings like "1h", "30m", "1 day".`);
	}

	// AWS only supports minute, hour, day - convert to the most appropriate unit
	const minutes = milliseconds / (1000 * 60);
	const hours = milliseconds / (1000 * 60 * 60);
	const days = milliseconds / (1000 * 60 * 60 * 24);

	// Choose the best unit (prefer larger units when they result in whole numbers)
	if (days >= 1 && Number.isInteger(days)) {
		return `rate(${days} ${days === 1 ? "day" : "days"})`;
	}
	if (hours >= 1 && Number.isInteger(hours)) {
		return `rate(${hours} ${hours === 1 ? "hour" : "hours"})`;
	}
	if (minutes >= 1 && Number.isInteger(minutes)) {
		return `rate(${minutes} ${minutes === 1 ? "minute" : "minutes"})`;
	}

	// If we can't get a whole number, round to nearest minute (minimum supported)
	const roundedMinutes = Math.max(1, Math.round(minutes));
	return `rate(${roundedMinutes} ${roundedMinutes === 1 ? "minute" : "minutes"})`;
}

/**
 * Process trigger config for Terraform output
 * Converts ms-style duration to AWS rate format for schedule triggers
 */
function processTriggerConfig(lambda: GenericLambdaManifest): {
	trigger_type: string;
	trigger_config: Record<string, unknown> | null;
} {
	const triggerType = lambda.trigger?.type ?? "";
	const triggerConfig = lambda.trigger?.config ?? null;

	// If it's a schedule trigger with 'every', convert to AWS rate format
	if (triggerType === "schedule" && triggerConfig && "every" in triggerConfig) {
		const { every, ...restConfig } = triggerConfig as { every: string; [key: string]: unknown };
		return {
			trigger_type: triggerType,
			trigger_config: {
				...restConfig,
				schedule_expression: convertMsToAwsRate(every),
			},
		};
	}

	return {
		trigger_type: triggerType,
		trigger_config: triggerConfig as Record<string, unknown> | null,
	};
}

/**
 * Generate API routes Terraform tfvars content from manifest
 */
export function generateApiRoutesTfvars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): string {
	// Get unique lambda names from routes (API routes only)
	const lambdaNames = [...new Set(manifest.routes.map((r) => r.lambda))];

	const routeEntries = manifest.routes.map((route) => {
		const routeName = generateRouteName(route.lambda, route.method, route.path);
		const apiGatewayRouteKey = `${route.method} ${route.apiGatewayPath}`;

		return `  ${routeName} = {
    lambda_key      = "${route.lambda}"
    route_key       = "${apiGatewayRouteKey}"
    path_parameters = ${JSON.stringify(route.pathParameters)}
  }`;
	});

	return `# Auto-generated by elysian - DO NOT EDIT
# Generated at: ${new Date().toISOString()}

# API route lambda names (from src/api/)
lambda_names = ${JSON.stringify(lambdaNames)}

api_routes = {
${routeEntries.join("\n")}
}

# Lambda configuration defaults
lambda_runtime     = "${config.lambda.runtime}"
lambda_memory_size = ${config.lambda.memorySize}
lambda_timeout     = ${config.lambda.timeout}
`;
}

/**
 * Generate functions Terraform tfvars content from manifest
 */
export function generateFunctionsTfvars(
	manifest: ApiManifest,
	_config: ResolvedConfig,
): string {
	// Build the generic_lambdas array format expected by Terraform
	// Include trigger type and config if present
	// For schedule triggers, convert ms-style 'every' to AWS rate expression
	const genericLambdas = manifest.genericLambdas.map((l) => {
		const { trigger_type, trigger_config } = processTriggerConfig(l);
		return {
			name: l.name,
			bundle_name: l.bundleName,
			trigger_type,
			trigger_config,
		};
	});

	return `# Auto-generated by elysian - DO NOT EDIT
# Generated at: ${new Date().toISOString()}

# Generic functions (from src/functions/)
generic_lambdas = ${JSON.stringify(genericLambdas, null, 2)}
`;
}

// Keep old function name for backwards compatibility
export const generateLambdasTfvars = generateFunctionsTfvars;

// Keep old function name for backwards compatibility
export function generateTerraformVars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): string {
	return generateApiRoutesTfvars(manifest, config);
}

/**
 * Write API routes Terraform tfvars file
 */
export async function writeApiRoutesTfvars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): Promise<string> {
	const tfvarsContent = generateApiRoutesTfvars(manifest, config);
	const outputPath = join(
		process.cwd(),
		config.terraform.outputDir,
		config.terraform.tfvarsFilename,
	);

	await Bun.write(outputPath, tfvarsContent);
	return outputPath;
}

/**
 * Write functions Terraform tfvars file
 */
export async function writeFunctionsTfvars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): Promise<string> {
	const tfvarsContent = generateFunctionsTfvars(manifest, config);
	const outputPath = join(
		process.cwd(),
		config.terraform.outputDir,
		config.terraform.functionsTfvarsFilename,
	);

	await Bun.write(outputPath, tfvarsContent);
	return outputPath;
}

// Keep old function name for backwards compatibility
export const writeLambdasTfvars = writeFunctionsTfvars;

/**
 * Write both Terraform tfvars files
 */
export async function writeTerraformVars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): Promise<{ apiRoutesPath: string; functionsPath: string }> {
	const apiRoutesPath = await writeApiRoutesTfvars(manifest, config);
	const functionsPath = await writeFunctionsTfvars(manifest, config);
	return { apiRoutesPath, functionsPath };
}
