/**
 * Terraform output generation
 */

import { join } from "path";
import type { ApiManifest } from "./manifest";
import type { ResolvedConfig } from "./config";
import { generateRouteName } from "./manifest";

/**
 * Generate Terraform tfvars content from manifest
 */
export function generateTerraformVars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): string {
	// Get unique lambda names from routes
	const lambdaNames = [...new Set(manifest.routes.map((r) => r.lambda))];

	const routeEntries = manifest.routes.map((route) => {
		const routeName = generateRouteName(route.lambda, route.method, route.path);
		const apiGatewayRouteKey = `${route.method} ${route.apiGatewayPath}`;

		return `  ${routeName} = {
    lambda_key      = "${route.lambda}"
    route_key       = "${apiGatewayRouteKey}"
    path_parameters = ${JSON.stringify(route.pathParameters)}
  }`;
	});

	return `# Auto-generated by elysian - DO NOT EDIT
# Generated at: ${new Date().toISOString()}

lambda_names = ${JSON.stringify(lambdaNames)}

api_routes = {
${routeEntries.join("\n")}
}

# Lambda configuration defaults
lambda_runtime     = "${config.lambda.runtime}"
lambda_memory_size = ${config.lambda.memorySize}
lambda_timeout     = ${config.lambda.timeout}
`;
}

/**
 * Write Terraform tfvars file
 */
export async function writeTerraformVars(
	manifest: ApiManifest,
	config: ResolvedConfig,
): Promise<string> {
	const tfvarsContent = generateTerraformVars(manifest, config);
	const outputPath = join(
		process.cwd(),
		config.terraform.outputDir,
		config.terraform.tfvarsFilename,
	);

	await Bun.write(outputPath, tfvarsContent);
	return outputPath;
}
